"""bugfix order number

Revision ID: 20b36e6cc7bf
Revises: c3846afa9c2d
Create Date: 2022-01-14 14:15:23.242244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b36e6cc7bf'
down_revision = 'c3846afa9c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('number', sa.String(length=10), nullable=True))
    op.drop_column('orders', 'numbers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('numbers', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('orders', 'number')
    # ### end Alembic commands ###
