"""bugfix

Revision ID: 21658d84e470
Revises: 20b36e6cc7bf
Create Date: 2022-01-14 14:18:47.370264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21658d84e470'
down_revision = '20b36e6cc7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
