"""added category, supplier and coupon

Revision ID: b9d158ed2720
Revises: abf9349bf1f0
Create Date: 2022-01-11 13:55:28.502034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d158ed2720'
down_revision = 'abf9349bf1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('expire_at', sa.DATETIME(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.drop_table('coupons')
    op.drop_table('categories')
    # ### end Alembic commands ###
